### ISSUE TITLE
This line through an error

### ISSUE THREAD

**Issue by ahmedtaa** [tresorsawasawa/Catalog_of_my_things#54]
Hi @tresorsawasawa 
This line through an error 
https://github.com/tresorsawasawa/Catalog_of_my_things/blob/9872609867cd6813273b45891dbbe7a0d169d672/app.rb#L1

![image](https://user-images.githubusercontent.com/1367194/165662900-2823a687-cc93-46c0-b25f-e1167883d7af.png)

**Comment by tresorsawasawa** [comment]
Hey @ahmedtaa 

It's working on my side

Are you still getting that arror? On my side everything is good

**Comment by ahmedtaa** [comment]
Hi @tresorsawasawa 

do you have a **console** folder in your project files?

![image](https://user-images.githubusercontent.com/1367194/165821573-bc4e838a-164f-47fb-814a-fa5e89838a28.png)

There are the project files of develop branch on GitHub, there is no such file called **console**!

**Comment by ahmedtaa** [comment]
Hi @tresorsawasawa 
I will mark this as solved, the problem is solved actually.
